version: "3"

services:
  post:
    tty: true
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: post-service-container
    working_dir: /go/src/github.com/SND1231/post-service
    ports:
      - "9002:9002"
    volumes:
      - ./src/db:/go/src/github.com/SND1231/post-service/db
      - ./src/go.mod:/go/src/github.com/SND1231/post-service/go.mod
      - ./src/go.sum:/go/src/github.com/SND1231/post-service/go.sum
      - ./src/main.go:/go/src/github.com/SND1231/post-service/main.go
      - ./src/migration:/go/src/github.com/SND1231/post-service/migration
      - ./src/model:/go/src/github.com/SND1231/post-service/model
      - ./src/post_app_service:/go/src/github.com/SND1231/post-service/post_app_service
      - ./src/post_service:/go/src/github.com/SND1231/post-service/post_service
    environment:
      DB_USER: root
      DB_PASSWORD: a1b2V4d
      DB_NAME: ramen_app
      DB_ADDRESS: db-post:3306
    networks:
      - app_network
  db-post:
    image: mysql:8.0
    restart: always
    container_name: mysql-post-container
    ports:
      - 23306:3306
    volumes:
      - ./mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: a1b2V4d
      MYSQL_DATABASE: ramen_app
    networks:
      - app_network

networks:
  app_network:
    external: true