version: "3"

services:
  post:
    tty: true
    build: ./docker
    container_name: post-service-container
    working_dir: /go/src/github.com/SND1231/post_service
    ports:
      - "9002:9002"
    volumes:
      - ./src:/go/src/github.com/SND1231/post_service
    environment:
      DB_USER: root
      DB_PASSWORD: a1b2V4d
      DB_NAME: ramen_app
      DB_ADDRESS: db-post:3306
    networks:
      - app_network
  db-post:
    image: mysql:8.0
    restart: always
    container_name: mysql-post-container
    ports:
      - 23306:3306
    volumes:
      - ./mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: a1b2V4d
      MYSQL_DATABASE: ramen_app
    networks:
      - app_network

networks:
  app_network:
    external: true